// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_CS_DC_RTABLE_POSITION_GET.proto

#ifndef PROTOBUF_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto__INCLUDED
#define PROTOBUF_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
void protobuf_AssignDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();

class MSG_CS_DC_RTABLE_POSITION_GET;
class MSG_DC_CS_RTABLE_POSITION_GET_ACK;

// ===================================================================

class MSG_CS_DC_RTABLE_POSITION_GET : public ::google::protobuf::Message {
 public:
  MSG_CS_DC_RTABLE_POSITION_GET();
  virtual ~MSG_CS_DC_RTABLE_POSITION_GET();
  
  MSG_CS_DC_RTABLE_POSITION_GET(const MSG_CS_DC_RTABLE_POSITION_GET& from);
  
  inline MSG_CS_DC_RTABLE_POSITION_GET& operator=(const MSG_CS_DC_RTABLE_POSITION_GET& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_CS_DC_RTABLE_POSITION_GET& default_instance();
  
  void Swap(MSG_CS_DC_RTABLE_POSITION_GET* other);
  
  // implements Message ----------------------------------------------
  
  MSG_CS_DC_RTABLE_POSITION_GET* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_CS_DC_RTABLE_POSITION_GET& from);
  void MergeFrom(const MSG_CS_DC_RTABLE_POSITION_GET& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 dbID = 1;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbIDFieldNumber = 1;
  inline ::google::protobuf::uint32 dbid() const;
  inline void set_dbid(::google::protobuf::uint32 value);
  
  // required string tableName = 2;
  inline bool has_tablename() const;
  inline void clear_tablename();
  static const int kTableNameFieldNumber = 2;
  inline const ::std::string& tablename() const;
  inline void set_tablename(const ::std::string& value);
  inline void set_tablename(const char* value);
  inline void set_tablename(const char* value, size_t size);
  inline ::std::string* mutable_tablename();
  inline ::std::string* release_tablename();
  
  // @@protoc_insertion_point(class_scope:MSG_CS_DC_RTABLE_POSITION_GET)
 private:
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_tablename();
  inline void clear_has_tablename();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* tablename_;
  ::google::protobuf::uint32 dbid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_CS_DC_RTABLE_POSITION_GET* default_instance_;
};
// -------------------------------------------------------------------

class MSG_DC_CS_RTABLE_POSITION_GET_ACK : public ::google::protobuf::Message {
 public:
  MSG_DC_CS_RTABLE_POSITION_GET_ACK();
  virtual ~MSG_DC_CS_RTABLE_POSITION_GET_ACK();
  
  MSG_DC_CS_RTABLE_POSITION_GET_ACK(const MSG_DC_CS_RTABLE_POSITION_GET_ACK& from);
  
  inline MSG_DC_CS_RTABLE_POSITION_GET_ACK& operator=(const MSG_DC_CS_RTABLE_POSITION_GET_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DC_CS_RTABLE_POSITION_GET_ACK& default_instance();
  
  void Swap(MSG_DC_CS_RTABLE_POSITION_GET_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DC_CS_RTABLE_POSITION_GET_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DC_CS_RTABLE_POSITION_GET_ACK& from);
  void MergeFrom(const MSG_DC_CS_RTABLE_POSITION_GET_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string csIP = 1;
  inline bool has_csip() const;
  inline void clear_csip();
  static const int kCsIPFieldNumber = 1;
  inline const ::std::string& csip() const;
  inline void set_csip(const ::std::string& value);
  inline void set_csip(const char* value);
  inline void set_csip(const char* value, size_t size);
  inline ::std::string* mutable_csip();
  inline ::std::string* release_csip();
  
  // required int32 statusCode = 2;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 2;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_DC_CS_RTABLE_POSITION_GET_ACK)
 private:
  inline void set_has_csip();
  inline void clear_has_csip();
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* csip_;
  ::google::protobuf::int32 statuscode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DC_CS_RTABLE_POSITION_GET_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_CS_DC_RTABLE_POSITION_GET

// required uint32 dbID = 1;
inline bool MSG_CS_DC_RTABLE_POSITION_GET::has_dbid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_has_dbid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::clear_dbid() {
  dbid_ = 0u;
  clear_has_dbid();
}
inline ::google::protobuf::uint32 MSG_CS_DC_RTABLE_POSITION_GET::dbid() const {
  return dbid_;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_dbid(::google::protobuf::uint32 value) {
  set_has_dbid();
  dbid_ = value;
}

// required string tableName = 2;
inline bool MSG_CS_DC_RTABLE_POSITION_GET::has_tablename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_has_tablename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::clear_has_tablename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::clear_tablename() {
  if (tablename_ != &::google::protobuf::internal::kEmptyString) {
    tablename_->clear();
  }
  clear_has_tablename();
}
inline const ::std::string& MSG_CS_DC_RTABLE_POSITION_GET::tablename() const {
  return *tablename_;
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_tablename(const ::std::string& value) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(value);
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_tablename(const char* value) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(value);
}
inline void MSG_CS_DC_RTABLE_POSITION_GET::set_tablename(const char* value, size_t size) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_CS_DC_RTABLE_POSITION_GET::mutable_tablename() {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  return tablename_;
}
inline ::std::string* MSG_CS_DC_RTABLE_POSITION_GET::release_tablename() {
  clear_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = tablename_;
    tablename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// MSG_DC_CS_RTABLE_POSITION_GET_ACK

// optional string csIP = 1;
inline bool MSG_DC_CS_RTABLE_POSITION_GET_ACK::has_csip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_has_csip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::clear_has_csip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::clear_csip() {
  if (csip_ != &::google::protobuf::internal::kEmptyString) {
    csip_->clear();
  }
  clear_has_csip();
}
inline const ::std::string& MSG_DC_CS_RTABLE_POSITION_GET_ACK::csip() const {
  return *csip_;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_csip(const ::std::string& value) {
  set_has_csip();
  if (csip_ == &::google::protobuf::internal::kEmptyString) {
    csip_ = new ::std::string;
  }
  csip_->assign(value);
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_csip(const char* value) {
  set_has_csip();
  if (csip_ == &::google::protobuf::internal::kEmptyString) {
    csip_ = new ::std::string;
  }
  csip_->assign(value);
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_csip(const char* value, size_t size) {
  set_has_csip();
  if (csip_ == &::google::protobuf::internal::kEmptyString) {
    csip_ = new ::std::string;
  }
  csip_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DC_CS_RTABLE_POSITION_GET_ACK::mutable_csip() {
  set_has_csip();
  if (csip_ == &::google::protobuf::internal::kEmptyString) {
    csip_ = new ::std::string;
  }
  return csip_;
}
inline ::std::string* MSG_DC_CS_RTABLE_POSITION_GET_ACK::release_csip() {
  clear_has_csip();
  if (csip_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = csip_;
    csip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 statusCode = 2;
inline bool MSG_DC_CS_RTABLE_POSITION_GET_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_DC_CS_RTABLE_POSITION_GET_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_DC_CS_RTABLE_POSITION_GET_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fCS_5fDC_5fRTABLE_5fPOSITION_5fGET_2eproto__INCLUDED
