// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MSG_DC_CS_SYSTEM_STATUS_GET.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DC_CS_SYSTEM_STATUS_GET_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_CS_DC_SYSTEM_STATUS_GET_ACK_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto() {
  protobuf_AddDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MSG_DC_CS_SYSTEM_STATUS_GET.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_ = file->message_type(0);
  static const int MSG_DC_CS_SYSTEM_STATUS_GET_offsets_[1] = {
  };
  MSG_DC_CS_SYSTEM_STATUS_GET_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_,
      MSG_DC_CS_SYSTEM_STATUS_GET::default_instance_,
      MSG_DC_CS_SYSTEM_STATUS_GET_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DC_CS_SYSTEM_STATUS_GET, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DC_CS_SYSTEM_STATUS_GET, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DC_CS_SYSTEM_STATUS_GET));
  MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_ = file->message_type(1);
  static const int MSG_CS_DC_SYSTEM_STATUS_GET_ACK_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DC_SYSTEM_STATUS_GET_ACK, statuscode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DC_SYSTEM_STATUS_GET_ACK, nodesysinfo_),
  };
  MSG_CS_DC_SYSTEM_STATUS_GET_ACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_,
      MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance_,
      MSG_CS_DC_SYSTEM_STATUS_GET_ACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DC_SYSTEM_STATUS_GET_ACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DC_SYSTEM_STATUS_GET_ACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_CS_DC_SYSTEM_STATUS_GET_ACK));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_, &MSG_DC_CS_SYSTEM_STATUS_GET::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_, &MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto() {
  delete MSG_DC_CS_SYSTEM_STATUS_GET::default_instance_;
  delete MSG_DC_CS_SYSTEM_STATUS_GET_reflection_;
  delete MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance_;
  delete MSG_CS_DC_SYSTEM_STATUS_GET_ACK_reflection_;
}

void protobuf_AddDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!MSG_DC_CS_SYSTEM_STATUS_GET.proto\032\014com"
    "mon.proto\"\035\n\033MSG_DC_CS_SYSTEM_STATUS_GET"
    "\"]\n\037MSG_CS_DC_SYSTEM_STATUS_GET_ACK\022\022\n\ns"
    "tatusCode\030\001 \002(\005\022&\n\013nodeSysInfo\030\002 \002(\0132\021.S"
    "INGLE_NODE_INFO", 175);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MSG_DC_CS_SYSTEM_STATUS_GET.proto", &protobuf_RegisterTypes);
  MSG_DC_CS_SYSTEM_STATUS_GET::default_instance_ = new MSG_DC_CS_SYSTEM_STATUS_GET();
  MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance_ = new MSG_CS_DC_SYSTEM_STATUS_GET_ACK();
  MSG_DC_CS_SYSTEM_STATUS_GET::default_instance_->InitAsDefaultInstance();
  MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto {
  StaticDescriptorInitializer_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto() {
    protobuf_AddDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto();
  }
} static_descriptor_initializer_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

MSG_DC_CS_SYSTEM_STATUS_GET::MSG_DC_CS_SYSTEM_STATUS_GET()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_DC_CS_SYSTEM_STATUS_GET::InitAsDefaultInstance() {
}

MSG_DC_CS_SYSTEM_STATUS_GET::MSG_DC_CS_SYSTEM_STATUS_GET(const MSG_DC_CS_SYSTEM_STATUS_GET& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_DC_CS_SYSTEM_STATUS_GET::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DC_CS_SYSTEM_STATUS_GET::~MSG_DC_CS_SYSTEM_STATUS_GET() {
  SharedDtor();
}

void MSG_DC_CS_SYSTEM_STATUS_GET::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MSG_DC_CS_SYSTEM_STATUS_GET::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DC_CS_SYSTEM_STATUS_GET::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_;
}

const MSG_DC_CS_SYSTEM_STATUS_GET& MSG_DC_CS_SYSTEM_STATUS_GET::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto();  return *default_instance_;
}

MSG_DC_CS_SYSTEM_STATUS_GET* MSG_DC_CS_SYSTEM_STATUS_GET::default_instance_ = NULL;

MSG_DC_CS_SYSTEM_STATUS_GET* MSG_DC_CS_SYSTEM_STATUS_GET::New() const {
  return new MSG_DC_CS_SYSTEM_STATUS_GET;
}

void MSG_DC_CS_SYSTEM_STATUS_GET::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DC_CS_SYSTEM_STATUS_GET::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void MSG_DC_CS_SYSTEM_STATUS_GET::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_DC_CS_SYSTEM_STATUS_GET::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_DC_CS_SYSTEM_STATUS_GET::ByteSize() const {
  int total_size = 0;
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DC_CS_SYSTEM_STATUS_GET::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DC_CS_SYSTEM_STATUS_GET* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DC_CS_SYSTEM_STATUS_GET*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DC_CS_SYSTEM_STATUS_GET::MergeFrom(const MSG_DC_CS_SYSTEM_STATUS_GET& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DC_CS_SYSTEM_STATUS_GET::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DC_CS_SYSTEM_STATUS_GET::CopyFrom(const MSG_DC_CS_SYSTEM_STATUS_GET& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DC_CS_SYSTEM_STATUS_GET::IsInitialized() const {
  
  return true;
}

void MSG_DC_CS_SYSTEM_STATUS_GET::Swap(MSG_DC_CS_SYSTEM_STATUS_GET* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DC_CS_SYSTEM_STATUS_GET::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DC_CS_SYSTEM_STATUS_GET_descriptor_;
  metadata.reflection = MSG_DC_CS_SYSTEM_STATUS_GET_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSG_CS_DC_SYSTEM_STATUS_GET_ACK::kStatusCodeFieldNumber;
const int MSG_CS_DC_SYSTEM_STATUS_GET_ACK::kNodeSysInfoFieldNumber;
#endif  // !_MSC_VER

MSG_CS_DC_SYSTEM_STATUS_GET_ACK::MSG_CS_DC_SYSTEM_STATUS_GET_ACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::InitAsDefaultInstance() {
  nodesysinfo_ = const_cast< ::SINGLE_NODE_INFO*>(&::SINGLE_NODE_INFO::default_instance());
}

MSG_CS_DC_SYSTEM_STATUS_GET_ACK::MSG_CS_DC_SYSTEM_STATUS_GET_ACK(const MSG_CS_DC_SYSTEM_STATUS_GET_ACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::SharedCtor() {
  _cached_size_ = 0;
  statuscode_ = 0;
  nodesysinfo_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_CS_DC_SYSTEM_STATUS_GET_ACK::~MSG_CS_DC_SYSTEM_STATUS_GET_ACK() {
  SharedDtor();
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::SharedDtor() {
  if (this != default_instance_) {
    delete nodesysinfo_;
  }
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_CS_DC_SYSTEM_STATUS_GET_ACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_;
}

const MSG_CS_DC_SYSTEM_STATUS_GET_ACK& MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDC_5fCS_5fSYSTEM_5fSTATUS_5fGET_2eproto();  return *default_instance_;
}

MSG_CS_DC_SYSTEM_STATUS_GET_ACK* MSG_CS_DC_SYSTEM_STATUS_GET_ACK::default_instance_ = NULL;

MSG_CS_DC_SYSTEM_STATUS_GET_ACK* MSG_CS_DC_SYSTEM_STATUS_GET_ACK::New() const {
  return new MSG_CS_DC_SYSTEM_STATUS_GET_ACK;
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    statuscode_ = 0;
    if (has_nodesysinfo()) {
      if (nodesysinfo_ != NULL) nodesysinfo_->::SINGLE_NODE_INFO::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_CS_DC_SYSTEM_STATUS_GET_ACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 statusCode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &statuscode_)));
          set_has_statuscode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_nodeSysInfo;
        break;
      }
      
      // required .SINGLE_NODE_INFO nodeSysInfo = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_nodeSysInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nodesysinfo()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 statusCode = 1;
  if (has_statuscode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->statuscode(), output);
  }
  
  // required .SINGLE_NODE_INFO nodeSysInfo = 2;
  if (has_nodesysinfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->nodesysinfo(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_CS_DC_SYSTEM_STATUS_GET_ACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 statusCode = 1;
  if (has_statuscode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->statuscode(), target);
  }
  
  // required .SINGLE_NODE_INFO nodeSysInfo = 2;
  if (has_nodesysinfo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->nodesysinfo(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_CS_DC_SYSTEM_STATUS_GET_ACK::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 statusCode = 1;
    if (has_statuscode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->statuscode());
    }
    
    // required .SINGLE_NODE_INFO nodeSysInfo = 2;
    if (has_nodesysinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->nodesysinfo());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_CS_DC_SYSTEM_STATUS_GET_ACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_CS_DC_SYSTEM_STATUS_GET_ACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::MergeFrom(const MSG_CS_DC_SYSTEM_STATUS_GET_ACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_statuscode()) {
      set_statuscode(from.statuscode());
    }
    if (from.has_nodesysinfo()) {
      mutable_nodesysinfo()->::SINGLE_NODE_INFO::MergeFrom(from.nodesysinfo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::CopyFrom(const MSG_CS_DC_SYSTEM_STATUS_GET_ACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_CS_DC_SYSTEM_STATUS_GET_ACK::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_nodesysinfo()) {
    if (!this->nodesysinfo().IsInitialized()) return false;
  }
  return true;
}

void MSG_CS_DC_SYSTEM_STATUS_GET_ACK::Swap(MSG_CS_DC_SYSTEM_STATUS_GET_ACK* other) {
  if (other != this) {
    std::swap(statuscode_, other->statuscode_);
    std::swap(nodesysinfo_, other->nodesysinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_CS_DC_SYSTEM_STATUS_GET_ACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_CS_DC_SYSTEM_STATUS_GET_ACK_descriptor_;
  metadata.reflection = MSG_CS_DC_SYSTEM_STATUS_GET_ACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
