// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_CS_DC_MEMORY_INFO_SEND.proto

#ifndef PROTOBUF_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto__INCLUDED
#define PROTOBUF_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
void protobuf_AssignDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();

class MSG_CS_DC_MEMORY_INFO_SEND;
class MSG_DC_CS_MEMORY_INFO_SEND_ACK;

// ===================================================================

class MSG_CS_DC_MEMORY_INFO_SEND : public ::google::protobuf::Message {
 public:
  MSG_CS_DC_MEMORY_INFO_SEND();
  virtual ~MSG_CS_DC_MEMORY_INFO_SEND();
  
  MSG_CS_DC_MEMORY_INFO_SEND(const MSG_CS_DC_MEMORY_INFO_SEND& from);
  
  inline MSG_CS_DC_MEMORY_INFO_SEND& operator=(const MSG_CS_DC_MEMORY_INFO_SEND& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_CS_DC_MEMORY_INFO_SEND& default_instance();
  
  void Swap(MSG_CS_DC_MEMORY_INFO_SEND* other);
  
  // implements Message ----------------------------------------------
  
  MSG_CS_DC_MEMORY_INFO_SEND* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_CS_DC_MEMORY_INFO_SEND& from);
  void MergeFrom(const MSG_CS_DC_MEMORY_INFO_SEND& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 memory = 1;
  inline bool has_memory() const;
  inline void clear_memory();
  static const int kMemoryFieldNumber = 1;
  inline ::google::protobuf::uint32 memory() const;
  inline void set_memory(::google::protobuf::uint32 value);
  
  // required uint32 port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_CS_DC_MEMORY_INFO_SEND)
 private:
  inline void set_has_memory();
  inline void clear_has_memory();
  inline void set_has_port();
  inline void clear_has_port();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 memory_;
  ::google::protobuf::uint32 port_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_CS_DC_MEMORY_INFO_SEND* default_instance_;
};
// -------------------------------------------------------------------

class MSG_DC_CS_MEMORY_INFO_SEND_ACK : public ::google::protobuf::Message {
 public:
  MSG_DC_CS_MEMORY_INFO_SEND_ACK();
  virtual ~MSG_DC_CS_MEMORY_INFO_SEND_ACK();
  
  MSG_DC_CS_MEMORY_INFO_SEND_ACK(const MSG_DC_CS_MEMORY_INFO_SEND_ACK& from);
  
  inline MSG_DC_CS_MEMORY_INFO_SEND_ACK& operator=(const MSG_DC_CS_MEMORY_INFO_SEND_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DC_CS_MEMORY_INFO_SEND_ACK& default_instance();
  
  void Swap(MSG_DC_CS_MEMORY_INFO_SEND_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DC_CS_MEMORY_INFO_SEND_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DC_CS_MEMORY_INFO_SEND_ACK& from);
  void MergeFrom(const MSG_DC_CS_MEMORY_INFO_SEND_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 statusCode = 1;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 statuscode() const;
  inline void set_statuscode(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_DC_CS_MEMORY_INFO_SEND_ACK)
 private:
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 statuscode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DC_CS_MEMORY_INFO_SEND_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_CS_DC_MEMORY_INFO_SEND

// required uint32 memory = 1;
inline bool MSG_CS_DC_MEMORY_INFO_SEND::has_memory() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::set_has_memory() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::clear_has_memory() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::clear_memory() {
  memory_ = 0u;
  clear_has_memory();
}
inline ::google::protobuf::uint32 MSG_CS_DC_MEMORY_INFO_SEND::memory() const {
  return memory_;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::set_memory(::google::protobuf::uint32 value) {
  set_has_memory();
  memory_ = value;
}

// required uint32 port = 2;
inline bool MSG_CS_DC_MEMORY_INFO_SEND::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 MSG_CS_DC_MEMORY_INFO_SEND::port() const {
  return port_;
}
inline void MSG_CS_DC_MEMORY_INFO_SEND::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
}

// -------------------------------------------------------------------

// MSG_DC_CS_MEMORY_INFO_SEND_ACK

// required uint32 statusCode = 1;
inline bool MSG_DC_CS_MEMORY_INFO_SEND_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DC_CS_MEMORY_INFO_SEND_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DC_CS_MEMORY_INFO_SEND_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DC_CS_MEMORY_INFO_SEND_ACK::clear_statuscode() {
  statuscode_ = 0u;
  clear_has_statuscode();
}
inline ::google::protobuf::uint32 MSG_DC_CS_MEMORY_INFO_SEND_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_DC_CS_MEMORY_INFO_SEND_ACK::set_statuscode(::google::protobuf::uint32 value) {
  set_has_statuscode();
  statuscode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fCS_5fDC_5fMEMORY_5fINFO_5fSEND_2eproto__INCLUDED
