// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MSG_DS_CS_RTABLE_CREATE.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_CREATE_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DS_CS_RTABLE_CREATE_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_CS_DS_RTABLE_CREATE_ACK_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto() {
  protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MSG_DS_CS_RTABLE_CREATE.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_DS_CS_RTABLE_CREATE_descriptor_ = file->message_type(0);
  static const int MSG_DS_CS_RTABLE_CREATE_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, taskid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, dbid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, tablename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, attributecount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, columnrtables_),
  };
  MSG_DS_CS_RTABLE_CREATE_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DS_CS_RTABLE_CREATE_descriptor_,
      MSG_DS_CS_RTABLE_CREATE::default_instance_,
      MSG_DS_CS_RTABLE_CREATE_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DS_CS_RTABLE_CREATE));
  MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_ = MSG_DS_CS_RTABLE_CREATE_descriptor_->nested_type(0);
  static const int MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE, columnname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE, entrylist_),
  };
  MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_,
      MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance_,
      MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE));
  MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_ = file->message_type(1);
  static const int MSG_CS_DS_RTABLE_CREATE_ACK_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DS_RTABLE_CREATE_ACK, statuscode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DS_RTABLE_CREATE_ACK, taskid_),
  };
  MSG_CS_DS_RTABLE_CREATE_ACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_,
      MSG_CS_DS_RTABLE_CREATE_ACK::default_instance_,
      MSG_CS_DS_RTABLE_CREATE_ACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DS_RTABLE_CREATE_ACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CS_DS_RTABLE_CREATE_ACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_CS_DS_RTABLE_CREATE_ACK));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DS_CS_RTABLE_CREATE_descriptor_, &MSG_DS_CS_RTABLE_CREATE::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_, &MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_, &MSG_CS_DS_RTABLE_CREATE_ACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto() {
  delete MSG_DS_CS_RTABLE_CREATE::default_instance_;
  delete MSG_DS_CS_RTABLE_CREATE_reflection_;
  delete MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance_;
  delete MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_reflection_;
  delete MSG_CS_DS_RTABLE_CREATE_ACK::default_instance_;
  delete MSG_CS_DS_RTABLE_CREATE_ACK_reflection_;
}

void protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035MSG_DS_CS_RTABLE_CREATE.proto\"\347\001\n\027MSG_"
    "DS_CS_RTABLE_CREATE\022\016\n\006taskID\030\001 \001(\r\022\014\n\004d"
    "bID\030\002 \001(\r\022\021\n\ttableName\030\003 \001(\t\022\026\n\016attribut"
    "eCount\030\004 \001(\r\022D\n\rcolumnRTables\030\005 \003(\0132-.MS"
    "G_DS_CS_RTABLE_CREATE.SINGLE_COLUMN_RTAB"
    "LE\032=\n\024SINGLE_COLUMN_RTABLE\022\022\n\ncolumnName"
    "\030\001 \001(\t\022\021\n\tentryList\030\002 \003(\004\"A\n\033MSG_CS_DS_R"
    "TABLE_CREATE_ACK\022\022\n\nstatusCode\030\001 \001(\005\022\016\n\006"
    "taskID\030\002 \001(\r", 332);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MSG_DS_CS_RTABLE_CREATE.proto", &protobuf_RegisterTypes);
  MSG_DS_CS_RTABLE_CREATE::default_instance_ = new MSG_DS_CS_RTABLE_CREATE();
  MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance_ = new MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE();
  MSG_CS_DS_RTABLE_CREATE_ACK::default_instance_ = new MSG_CS_DS_RTABLE_CREATE_ACK();
  MSG_DS_CS_RTABLE_CREATE::default_instance_->InitAsDefaultInstance();
  MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance_->InitAsDefaultInstance();
  MSG_CS_DS_RTABLE_CREATE_ACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto {
  StaticDescriptorInitializer_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto() {
    protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto();
  }
} static_descriptor_initializer_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::kColumnNameFieldNumber;
const int MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::kEntryListFieldNumber;
#endif  // !_MSC_VER

MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::InitAsDefaultInstance() {
}

MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE(const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::SharedCtor() {
  _cached_size_ = 0;
  columnname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::~MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE() {
  SharedDtor();
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::SharedDtor() {
  if (columnname_ != &::google::protobuf::internal::kEmptyString) {
    delete columnname_;
  }
  if (this != default_instance_) {
  }
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_;
}

const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE& MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto();  return *default_instance_;
}

MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE* MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::default_instance_ = NULL;

MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE* MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::New() const {
  return new MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE;
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_columnname()) {
      if (columnname_ != &::google::protobuf::internal::kEmptyString) {
        columnname_->clear();
      }
    }
  }
  entrylist_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string columnName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_columnname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->columnname().data(), this->columnname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_entryList;
        break;
      }
      
      // repeated uint64 entryList = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_entryList:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16, input, this->mutable_entrylist())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_entrylist())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_entryList;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string columnName = 1;
  if (has_columnname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->columnname().data(), this->columnname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->columnname(), output);
  }
  
  // repeated uint64 entryList = 2;
  for (int i = 0; i < this->entrylist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->entrylist(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string columnName = 1;
  if (has_columnname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->columnname().data(), this->columnname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->columnname(), target);
  }
  
  // repeated uint64 entryList = 2;
  for (int i = 0; i < this->entrylist_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(2, this->entrylist(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string columnName = 1;
    if (has_columnname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->columnname());
    }
    
  }
  // repeated uint64 entryList = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->entrylist_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->entrylist(i));
    }
    total_size += 1 * this->entrylist_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::MergeFrom(const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE& from) {
  GOOGLE_CHECK_NE(&from, this);
  entrylist_.MergeFrom(from.entrylist_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_columnname()) {
      set_columnname(from.columnname());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::CopyFrom(const MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::IsInitialized() const {
  
  return true;
}

void MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::Swap(MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE* other) {
  if (other != this) {
    std::swap(columnname_, other->columnname_);
    entrylist_.Swap(&other->entrylist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_descriptor_;
  metadata.reflection = MSG_DS_CS_RTABLE_CREATE_SINGLE_COLUMN_RTABLE_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MSG_DS_CS_RTABLE_CREATE::kTaskIDFieldNumber;
const int MSG_DS_CS_RTABLE_CREATE::kDbIDFieldNumber;
const int MSG_DS_CS_RTABLE_CREATE::kTableNameFieldNumber;
const int MSG_DS_CS_RTABLE_CREATE::kAttributeCountFieldNumber;
const int MSG_DS_CS_RTABLE_CREATE::kColumnRTablesFieldNumber;
#endif  // !_MSC_VER

MSG_DS_CS_RTABLE_CREATE::MSG_DS_CS_RTABLE_CREATE()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_DS_CS_RTABLE_CREATE::InitAsDefaultInstance() {
}

MSG_DS_CS_RTABLE_CREATE::MSG_DS_CS_RTABLE_CREATE(const MSG_DS_CS_RTABLE_CREATE& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_CREATE::SharedCtor() {
  _cached_size_ = 0;
  taskid_ = 0u;
  dbid_ = 0u;
  tablename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  attributecount_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DS_CS_RTABLE_CREATE::~MSG_DS_CS_RTABLE_CREATE() {
  SharedDtor();
}

void MSG_DS_CS_RTABLE_CREATE::SharedDtor() {
  if (tablename_ != &::google::protobuf::internal::kEmptyString) {
    delete tablename_;
  }
  if (this != default_instance_) {
  }
}

void MSG_DS_CS_RTABLE_CREATE::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_CREATE::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DS_CS_RTABLE_CREATE_descriptor_;
}

const MSG_DS_CS_RTABLE_CREATE& MSG_DS_CS_RTABLE_CREATE::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto();  return *default_instance_;
}

MSG_DS_CS_RTABLE_CREATE* MSG_DS_CS_RTABLE_CREATE::default_instance_ = NULL;

MSG_DS_CS_RTABLE_CREATE* MSG_DS_CS_RTABLE_CREATE::New() const {
  return new MSG_DS_CS_RTABLE_CREATE;
}

void MSG_DS_CS_RTABLE_CREATE::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    taskid_ = 0u;
    dbid_ = 0u;
    if (has_tablename()) {
      if (tablename_ != &::google::protobuf::internal::kEmptyString) {
        tablename_->clear();
      }
    }
    attributecount_ = 0u;
  }
  columnrtables_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DS_CS_RTABLE_CREATE::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 taskID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &taskid_)));
          set_has_taskid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_dbID;
        break;
      }
      
      // optional uint32 dbID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dbID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dbid_)));
          set_has_dbid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_tableName;
        break;
      }
      
      // optional string tableName = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tableName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tablename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->tablename().data(), this->tablename().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_attributeCount;
        break;
      }
      
      // optional uint32 attributeCount = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_attributeCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &attributecount_)));
          set_has_attributecount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_columnRTables;
        break;
      }
      
      // repeated .MSG_DS_CS_RTABLE_CREATE.SINGLE_COLUMN_RTABLE columnRTables = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_columnRTables:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_columnrtables()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_columnRTables;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_DS_CS_RTABLE_CREATE::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 taskID = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->taskid(), output);
  }
  
  // optional uint32 dbID = 2;
  if (has_dbid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dbid(), output);
  }
  
  // optional string tableName = 3;
  if (has_tablename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->tablename().data(), this->tablename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->tablename(), output);
  }
  
  // optional uint32 attributeCount = 4;
  if (has_attributecount()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->attributecount(), output);
  }
  
  // repeated .MSG_DS_CS_RTABLE_CREATE.SINGLE_COLUMN_RTABLE columnRTables = 5;
  for (int i = 0; i < this->columnrtables_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->columnrtables(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_DS_CS_RTABLE_CREATE::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint32 taskID = 1;
  if (has_taskid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->taskid(), target);
  }
  
  // optional uint32 dbID = 2;
  if (has_dbid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dbid(), target);
  }
  
  // optional string tableName = 3;
  if (has_tablename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->tablename().data(), this->tablename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->tablename(), target);
  }
  
  // optional uint32 attributeCount = 4;
  if (has_attributecount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->attributecount(), target);
  }
  
  // repeated .MSG_DS_CS_RTABLE_CREATE.SINGLE_COLUMN_RTABLE columnRTables = 5;
  for (int i = 0; i < this->columnrtables_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->columnrtables(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_DS_CS_RTABLE_CREATE::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 taskID = 1;
    if (has_taskid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->taskid());
    }
    
    // optional uint32 dbID = 2;
    if (has_dbid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dbid());
    }
    
    // optional string tableName = 3;
    if (has_tablename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->tablename());
    }
    
    // optional uint32 attributeCount = 4;
    if (has_attributecount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->attributecount());
    }
    
  }
  // repeated .MSG_DS_CS_RTABLE_CREATE.SINGLE_COLUMN_RTABLE columnRTables = 5;
  total_size += 1 * this->columnrtables_size();
  for (int i = 0; i < this->columnrtables_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->columnrtables(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DS_CS_RTABLE_CREATE::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DS_CS_RTABLE_CREATE* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DS_CS_RTABLE_CREATE*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DS_CS_RTABLE_CREATE::MergeFrom(const MSG_DS_CS_RTABLE_CREATE& from) {
  GOOGLE_CHECK_NE(&from, this);
  columnrtables_.MergeFrom(from.columnrtables_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_taskid()) {
      set_taskid(from.taskid());
    }
    if (from.has_dbid()) {
      set_dbid(from.dbid());
    }
    if (from.has_tablename()) {
      set_tablename(from.tablename());
    }
    if (from.has_attributecount()) {
      set_attributecount(from.attributecount());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DS_CS_RTABLE_CREATE::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_CREATE::CopyFrom(const MSG_DS_CS_RTABLE_CREATE& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DS_CS_RTABLE_CREATE::IsInitialized() const {
  
  return true;
}

void MSG_DS_CS_RTABLE_CREATE::Swap(MSG_DS_CS_RTABLE_CREATE* other) {
  if (other != this) {
    std::swap(taskid_, other->taskid_);
    std::swap(dbid_, other->dbid_);
    std::swap(tablename_, other->tablename_);
    std::swap(attributecount_, other->attributecount_);
    columnrtables_.Swap(&other->columnrtables_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DS_CS_RTABLE_CREATE::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DS_CS_RTABLE_CREATE_descriptor_;
  metadata.reflection = MSG_DS_CS_RTABLE_CREATE_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSG_CS_DS_RTABLE_CREATE_ACK::kStatusCodeFieldNumber;
const int MSG_CS_DS_RTABLE_CREATE_ACK::kTaskIDFieldNumber;
#endif  // !_MSC_VER

MSG_CS_DS_RTABLE_CREATE_ACK::MSG_CS_DS_RTABLE_CREATE_ACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_CS_DS_RTABLE_CREATE_ACK::InitAsDefaultInstance() {
}

MSG_CS_DS_RTABLE_CREATE_ACK::MSG_CS_DS_RTABLE_CREATE_ACK(const MSG_CS_DS_RTABLE_CREATE_ACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_CS_DS_RTABLE_CREATE_ACK::SharedCtor() {
  _cached_size_ = 0;
  statuscode_ = 0;
  taskid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_CS_DS_RTABLE_CREATE_ACK::~MSG_CS_DS_RTABLE_CREATE_ACK() {
  SharedDtor();
}

void MSG_CS_DS_RTABLE_CREATE_ACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MSG_CS_DS_RTABLE_CREATE_ACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_CS_DS_RTABLE_CREATE_ACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_;
}

const MSG_CS_DS_RTABLE_CREATE_ACK& MSG_CS_DS_RTABLE_CREATE_ACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fCREATE_2eproto();  return *default_instance_;
}

MSG_CS_DS_RTABLE_CREATE_ACK* MSG_CS_DS_RTABLE_CREATE_ACK::default_instance_ = NULL;

MSG_CS_DS_RTABLE_CREATE_ACK* MSG_CS_DS_RTABLE_CREATE_ACK::New() const {
  return new MSG_CS_DS_RTABLE_CREATE_ACK;
}

void MSG_CS_DS_RTABLE_CREATE_ACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    statuscode_ = 0;
    taskid_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_CS_DS_RTABLE_CREATE_ACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 statusCode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &statuscode_)));
          set_has_statuscode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_taskID;
        break;
      }
      
      // optional uint32 taskID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_taskID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &taskid_)));
          set_has_taskid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_CS_DS_RTABLE_CREATE_ACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 statusCode = 1;
  if (has_statuscode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->statuscode(), output);
  }
  
  // optional uint32 taskID = 2;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->taskid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_CS_DS_RTABLE_CREATE_ACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 statusCode = 1;
  if (has_statuscode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->statuscode(), target);
  }
  
  // optional uint32 taskID = 2;
  if (has_taskid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->taskid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_CS_DS_RTABLE_CREATE_ACK::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 statusCode = 1;
    if (has_statuscode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->statuscode());
    }
    
    // optional uint32 taskID = 2;
    if (has_taskid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->taskid());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_CS_DS_RTABLE_CREATE_ACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_CS_DS_RTABLE_CREATE_ACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_CS_DS_RTABLE_CREATE_ACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_CS_DS_RTABLE_CREATE_ACK::MergeFrom(const MSG_CS_DS_RTABLE_CREATE_ACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_statuscode()) {
      set_statuscode(from.statuscode());
    }
    if (from.has_taskid()) {
      set_taskid(from.taskid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_CS_DS_RTABLE_CREATE_ACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_CS_DS_RTABLE_CREATE_ACK::CopyFrom(const MSG_CS_DS_RTABLE_CREATE_ACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_CS_DS_RTABLE_CREATE_ACK::IsInitialized() const {
  
  return true;
}

void MSG_CS_DS_RTABLE_CREATE_ACK::Swap(MSG_CS_DS_RTABLE_CREATE_ACK* other) {
  if (other != this) {
    std::swap(statuscode_, other->statuscode_);
    std::swap(taskid_, other->taskid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_CS_DS_RTABLE_CREATE_ACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_CS_DS_RTABLE_CREATE_ACK_descriptor_;
  metadata.reflection = MSG_CS_DS_RTABLE_CREATE_ACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
