// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_DS_CS_RAW_DATA_SEND.proto

#ifndef PROTOBUF_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto__INCLUDED
#define PROTOBUF_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
void protobuf_AssignDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
void protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();

class MSG_DS_CS_RAW_DATA_SEND;
class MSG_CS_DS_RAW_DATA_SEND_ACK;

enum MSG_DS_CS_RAW_DATA_SEND_COL_TYPE {
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_VARCHAR = 0,
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_INTTYPE = 1,
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_DOUBLETYPE = 2,
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_TEXT = 3,
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_BLOB = 4,
  MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_TIMESTAMP = 5
};
bool MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_IsValid(int value);
const MSG_DS_CS_RAW_DATA_SEND_COL_TYPE MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_MIN = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_VARCHAR;
const MSG_DS_CS_RAW_DATA_SEND_COL_TYPE MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_MAX = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_TIMESTAMP;
const int MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_ARRAYSIZE = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_descriptor();
inline const ::std::string& MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_Name(MSG_DS_CS_RAW_DATA_SEND_COL_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_descriptor(), value);
}
inline bool MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_Parse(
    const ::std::string& name, MSG_DS_CS_RAW_DATA_SEND_COL_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG_DS_CS_RAW_DATA_SEND_COL_TYPE>(
    MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_descriptor(), name, value);
}
// ===================================================================

class MSG_DS_CS_RAW_DATA_SEND : public ::google::protobuf::Message {
 public:
  MSG_DS_CS_RAW_DATA_SEND();
  virtual ~MSG_DS_CS_RAW_DATA_SEND();
  
  MSG_DS_CS_RAW_DATA_SEND(const MSG_DS_CS_RAW_DATA_SEND& from);
  
  inline MSG_DS_CS_RAW_DATA_SEND& operator=(const MSG_DS_CS_RAW_DATA_SEND& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DS_CS_RAW_DATA_SEND& default_instance();
  
  void Swap(MSG_DS_CS_RAW_DATA_SEND* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DS_CS_RAW_DATA_SEND* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DS_CS_RAW_DATA_SEND& from);
  void MergeFrom(const MSG_DS_CS_RAW_DATA_SEND& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef MSG_DS_CS_RAW_DATA_SEND_COL_TYPE COL_TYPE;
  static const COL_TYPE VARCHAR = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_VARCHAR;
  static const COL_TYPE INTTYPE = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_INTTYPE;
  static const COL_TYPE DOUBLETYPE = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_DOUBLETYPE;
  static const COL_TYPE TEXT = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_TEXT;
  static const COL_TYPE BLOB = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_BLOB;
  static const COL_TYPE TIMESTAMP = MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_TIMESTAMP;
  static inline bool COL_TYPE_IsValid(int value) {
    return MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_IsValid(value);
  }
  static const COL_TYPE COL_TYPE_MIN =
    MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_MIN;
  static const COL_TYPE COL_TYPE_MAX =
    MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_MAX;
  static const int COL_TYPE_ARRAYSIZE =
    MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_COL_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  COL_TYPE_descriptor() {
    return MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_descriptor();
  }
  static inline const ::std::string& COL_TYPE_Name(COL_TYPE value) {
    return MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_Name(value);
  }
  static inline bool COL_TYPE_Parse(const ::std::string& name,
      COL_TYPE* value) {
    return MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required uint32 taskID = 1;
  inline bool has_taskid() const;
  inline void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  inline ::google::protobuf::uint32 taskid() const;
  inline void set_taskid(::google::protobuf::uint32 value);
  
  // required uint32 dbID = 2;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbIDFieldNumber = 2;
  inline ::google::protobuf::uint32 dbid() const;
  inline void set_dbid(::google::protobuf::uint32 value);
  
  // required string tableName = 3;
  inline bool has_tablename() const;
  inline void clear_tablename();
  static const int kTableNameFieldNumber = 3;
  inline const ::std::string& tablename() const;
  inline void set_tablename(const ::std::string& value);
  inline void set_tablename(const char* value);
  inline void set_tablename(const char* value, size_t size);
  inline ::std::string* mutable_tablename();
  inline ::std::string* release_tablename();
  
  // required string columnName = 4;
  inline bool has_columnname() const;
  inline void clear_columnname();
  static const int kColumnNameFieldNumber = 4;
  inline const ::std::string& columnname() const;
  inline void set_columnname(const ::std::string& value);
  inline void set_columnname(const char* value);
  inline void set_columnname(const char* value, size_t size);
  inline ::std::string* mutable_columnname();
  inline ::std::string* release_columnname();
  
  // required .MSG_DS_CS_RAW_DATA_SEND.COL_TYPE columnType = 5;
  inline bool has_columntype() const;
  inline void clear_columntype();
  static const int kColumnTypeFieldNumber = 5;
  inline ::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE columntype() const;
  inline void set_columntype(::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE value);
  
  // repeated .DICT_VALUE dicValue = 6;
  inline int dicvalue_size() const;
  inline void clear_dicvalue();
  static const int kDicValueFieldNumber = 6;
  inline const ::DICT_VALUE& dicvalue(int index) const;
  inline ::DICT_VALUE* mutable_dicvalue(int index);
  inline ::DICT_VALUE* add_dicvalue();
  inline const ::google::protobuf::RepeatedPtrField< ::DICT_VALUE >&
      dicvalue() const;
  inline ::google::protobuf::RepeatedPtrField< ::DICT_VALUE >*
      mutable_dicvalue();
  
  // repeated uint32 indexOffsets = 7;
  inline int indexoffsets_size() const;
  inline void clear_indexoffsets();
  static const int kIndexOffsetsFieldNumber = 7;
  inline ::google::protobuf::uint32 indexoffsets(int index) const;
  inline void set_indexoffsets(int index, ::google::protobuf::uint32 value);
  inline void add_indexoffsets(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      indexoffsets() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_indexoffsets();
  
  // repeated uint32 indexPosting = 8;
  inline int indexposting_size() const;
  inline void clear_indexposting();
  static const int kIndexPostingFieldNumber = 8;
  inline ::google::protobuf::uint32 indexposting(int index) const;
  inline void set_indexposting(int index, ::google::protobuf::uint32 value);
  inline void add_indexposting(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      indexposting() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_indexposting();
  
  // optional uint32 sliceNo = 9;
  inline bool has_sliceno() const;
  inline void clear_sliceno();
  static const int kSliceNoFieldNumber = 9;
  inline ::google::protobuf::uint32 sliceno() const;
  inline void set_sliceno(::google::protobuf::uint32 value);
  
  // optional uint32 sliceNum = 10;
  inline bool has_slicenum() const;
  inline void clear_slicenum();
  static const int kSliceNumFieldNumber = 10;
  inline ::google::protobuf::uint32 slicenum() const;
  inline void set_slicenum(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_DS_CS_RAW_DATA_SEND)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_tablename();
  inline void clear_has_tablename();
  inline void set_has_columnname();
  inline void clear_has_columnname();
  inline void set_has_columntype();
  inline void clear_has_columntype();
  inline void set_has_sliceno();
  inline void clear_has_sliceno();
  inline void set_has_slicenum();
  inline void clear_has_slicenum();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 taskid_;
  ::google::protobuf::uint32 dbid_;
  ::std::string* tablename_;
  ::std::string* columnname_;
  ::google::protobuf::RepeatedPtrField< ::DICT_VALUE > dicvalue_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > indexoffsets_;
  int columntype_;
  ::google::protobuf::uint32 sliceno_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > indexposting_;
  ::google::protobuf::uint32 slicenum_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DS_CS_RAW_DATA_SEND* default_instance_;
};
// -------------------------------------------------------------------

class MSG_CS_DS_RAW_DATA_SEND_ACK : public ::google::protobuf::Message {
 public:
  MSG_CS_DS_RAW_DATA_SEND_ACK();
  virtual ~MSG_CS_DS_RAW_DATA_SEND_ACK();
  
  MSG_CS_DS_RAW_DATA_SEND_ACK(const MSG_CS_DS_RAW_DATA_SEND_ACK& from);
  
  inline MSG_CS_DS_RAW_DATA_SEND_ACK& operator=(const MSG_CS_DS_RAW_DATA_SEND_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_CS_DS_RAW_DATA_SEND_ACK& default_instance();
  
  void Swap(MSG_CS_DS_RAW_DATA_SEND_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_CS_DS_RAW_DATA_SEND_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_CS_DS_RAW_DATA_SEND_ACK& from);
  void MergeFrom(const MSG_CS_DS_RAW_DATA_SEND_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 taskID = 1;
  inline bool has_taskid() const;
  inline void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  inline ::google::protobuf::uint32 taskid() const;
  inline void set_taskid(::google::protobuf::uint32 value);
  
  // required int32 statusCode = 2;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 2;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);
  
  // required string columnName = 3;
  inline bool has_columnname() const;
  inline void clear_columnname();
  static const int kColumnNameFieldNumber = 3;
  inline const ::std::string& columnname() const;
  inline void set_columnname(const ::std::string& value);
  inline void set_columnname(const char* value);
  inline void set_columnname(const char* value, size_t size);
  inline ::std::string* mutable_columnname();
  inline ::std::string* release_columnname();
  
  // @@protoc_insertion_point(class_scope:MSG_CS_DS_RAW_DATA_SEND_ACK)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  inline void set_has_columnname();
  inline void clear_has_columnname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 taskid_;
  ::google::protobuf::int32 statuscode_;
  ::std::string* columnname_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_CS_DS_RAW_DATA_SEND_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_DS_CS_RAW_DATA_SEND

// required uint32 taskID = 1;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_taskid() {
  taskid_ = 0u;
  clear_has_taskid();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::taskid() const {
  return taskid_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_taskid(::google::protobuf::uint32 value) {
  set_has_taskid();
  taskid_ = value;
}

// required uint32 dbID = 2;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_dbid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_dbid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_dbid() {
  dbid_ = 0u;
  clear_has_dbid();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::dbid() const {
  return dbid_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_dbid(::google::protobuf::uint32 value) {
  set_has_dbid();
  dbid_ = value;
}

// required string tableName = 3;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_tablename() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_tablename() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_tablename() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_tablename() {
  if (tablename_ != &::google::protobuf::internal::kEmptyString) {
    tablename_->clear();
  }
  clear_has_tablename();
}
inline const ::std::string& MSG_DS_CS_RAW_DATA_SEND::tablename() const {
  return *tablename_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_tablename(const ::std::string& value) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_tablename(const char* value) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_tablename(const char* value, size_t size) {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  tablename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DS_CS_RAW_DATA_SEND::mutable_tablename() {
  set_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    tablename_ = new ::std::string;
  }
  return tablename_;
}
inline ::std::string* MSG_DS_CS_RAW_DATA_SEND::release_tablename() {
  clear_has_tablename();
  if (tablename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = tablename_;
    tablename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string columnName = 4;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_columnname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_columnname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_columnname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_columnname() {
  if (columnname_ != &::google::protobuf::internal::kEmptyString) {
    columnname_->clear();
  }
  clear_has_columnname();
}
inline const ::std::string& MSG_DS_CS_RAW_DATA_SEND::columnname() const {
  return *columnname_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_columnname(const ::std::string& value) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_columnname(const char* value) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_columnname(const char* value, size_t size) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DS_CS_RAW_DATA_SEND::mutable_columnname() {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  return columnname_;
}
inline ::std::string* MSG_DS_CS_RAW_DATA_SEND::release_columnname() {
  clear_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = columnname_;
    columnname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .MSG_DS_CS_RAW_DATA_SEND.COL_TYPE columnType = 5;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_columntype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_columntype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_columntype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_columntype() {
  columntype_ = 0;
  clear_has_columntype();
}
inline ::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE MSG_DS_CS_RAW_DATA_SEND::columntype() const {
  return static_cast< ::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE >(columntype_);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_columntype(::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE value) {
  GOOGLE_DCHECK(::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_IsValid(value));
  set_has_columntype();
  columntype_ = value;
}

// repeated .DICT_VALUE dicValue = 6;
inline int MSG_DS_CS_RAW_DATA_SEND::dicvalue_size() const {
  return dicvalue_.size();
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_dicvalue() {
  dicvalue_.Clear();
}
inline const ::DICT_VALUE& MSG_DS_CS_RAW_DATA_SEND::dicvalue(int index) const {
  return dicvalue_.Get(index);
}
inline ::DICT_VALUE* MSG_DS_CS_RAW_DATA_SEND::mutable_dicvalue(int index) {
  return dicvalue_.Mutable(index);
}
inline ::DICT_VALUE* MSG_DS_CS_RAW_DATA_SEND::add_dicvalue() {
  return dicvalue_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DICT_VALUE >&
MSG_DS_CS_RAW_DATA_SEND::dicvalue() const {
  return dicvalue_;
}
inline ::google::protobuf::RepeatedPtrField< ::DICT_VALUE >*
MSG_DS_CS_RAW_DATA_SEND::mutable_dicvalue() {
  return &dicvalue_;
}

// repeated uint32 indexOffsets = 7;
inline int MSG_DS_CS_RAW_DATA_SEND::indexoffsets_size() const {
  return indexoffsets_.size();
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_indexoffsets() {
  indexoffsets_.Clear();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::indexoffsets(int index) const {
  return indexoffsets_.Get(index);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_indexoffsets(int index, ::google::protobuf::uint32 value) {
  indexoffsets_.Set(index, value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::add_indexoffsets(::google::protobuf::uint32 value) {
  indexoffsets_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
MSG_DS_CS_RAW_DATA_SEND::indexoffsets() const {
  return indexoffsets_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
MSG_DS_CS_RAW_DATA_SEND::mutable_indexoffsets() {
  return &indexoffsets_;
}

// repeated uint32 indexPosting = 8;
inline int MSG_DS_CS_RAW_DATA_SEND::indexposting_size() const {
  return indexposting_.size();
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_indexposting() {
  indexposting_.Clear();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::indexposting(int index) const {
  return indexposting_.Get(index);
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_indexposting(int index, ::google::protobuf::uint32 value) {
  indexposting_.Set(index, value);
}
inline void MSG_DS_CS_RAW_DATA_SEND::add_indexposting(::google::protobuf::uint32 value) {
  indexposting_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
MSG_DS_CS_RAW_DATA_SEND::indexposting() const {
  return indexposting_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
MSG_DS_CS_RAW_DATA_SEND::mutable_indexposting() {
  return &indexposting_;
}

// optional uint32 sliceNo = 9;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_sliceno() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_sliceno() {
  _has_bits_[0] |= 0x00000100u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_sliceno() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_sliceno() {
  sliceno_ = 0u;
  clear_has_sliceno();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::sliceno() const {
  return sliceno_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_sliceno(::google::protobuf::uint32 value) {
  set_has_sliceno();
  sliceno_ = value;
}

// optional uint32 sliceNum = 10;
inline bool MSG_DS_CS_RAW_DATA_SEND::has_slicenum() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_has_slicenum() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_has_slicenum() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MSG_DS_CS_RAW_DATA_SEND::clear_slicenum() {
  slicenum_ = 0u;
  clear_has_slicenum();
}
inline ::google::protobuf::uint32 MSG_DS_CS_RAW_DATA_SEND::slicenum() const {
  return slicenum_;
}
inline void MSG_DS_CS_RAW_DATA_SEND::set_slicenum(::google::protobuf::uint32 value) {
  set_has_slicenum();
  slicenum_ = value;
}

// -------------------------------------------------------------------

// MSG_CS_DS_RAW_DATA_SEND_ACK

// required uint32 taskID = 1;
inline bool MSG_CS_DS_RAW_DATA_SEND_ACK::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_taskid() {
  taskid_ = 0u;
  clear_has_taskid();
}
inline ::google::protobuf::uint32 MSG_CS_DS_RAW_DATA_SEND_ACK::taskid() const {
  return taskid_;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_taskid(::google::protobuf::uint32 value) {
  set_has_taskid();
  taskid_ = value;
}

// required int32 statusCode = 2;
inline bool MSG_CS_DS_RAW_DATA_SEND_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_CS_DS_RAW_DATA_SEND_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
}

// required string columnName = 3;
inline bool MSG_CS_DS_RAW_DATA_SEND_ACK::has_columnname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_has_columnname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_has_columnname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::clear_columnname() {
  if (columnname_ != &::google::protobuf::internal::kEmptyString) {
    columnname_->clear();
  }
  clear_has_columnname();
}
inline const ::std::string& MSG_CS_DS_RAW_DATA_SEND_ACK::columnname() const {
  return *columnname_;
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_columnname(const ::std::string& value) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(value);
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_columnname(const char* value) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(value);
}
inline void MSG_CS_DS_RAW_DATA_SEND_ACK::set_columnname(const char* value, size_t size) {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  columnname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_CS_DS_RAW_DATA_SEND_ACK::mutable_columnname() {
  set_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    columnname_ = new ::std::string;
  }
  return columnname_;
}
inline ::std::string* MSG_CS_DS_RAW_DATA_SEND_ACK::release_columnname() {
  clear_has_columnname();
  if (columnname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = columnname_;
    columnname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE>() {
  return ::MSG_DS_CS_RAW_DATA_SEND_COL_TYPE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fDS_5fCS_5fRAW_5fDATA_5fSEND_2eproto__INCLUDED
